[target.x86_64-apple-darwin]
rustflags = ["-C", "default-linker-libraries", "-C", "link-args=-Wl,-rpath,/usr/lib/swift"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "default-linker-libraries", "-C", "link-args=-Wl,-rpath,/usr/lib/swift"]

[target.aarch64-apple-ios]
rustflags = ["-C", "default-linker-libraries", "-C", "link-args=-Wl,-rpath,/usr/lib/swift"]
